### ISSUE TITLE
How to use CSS Modeules together?

### ISSUE THREAD

**Issue by Shyam-Chen** [bdadam/rollup-plugin-html#3]
```html
<!-- home.html -->
<div class="${homeStyl.title}">  <!-- <= Note! -->
  Home
</div>
```
```css
// home.css
.title {
  color: red;
}
```
```js
// home.js
import homeStyl from './home.css';
import homeTpl from './home.html';

document.querySelector('#home').innerHTML = ??
```
```js
// home.js
import homeStyl from './home.css';

document.querySelector('#home').innerHTML = `
  <div class="${homeStyl.title}">
    Home
  </div>
`;
```

**Comment by bdadam** [comment]
Hi @Shyam-Chen, sorry for the late response. What you are asking for is not completely impossible. I think the best would be to use some kind of templating (e.g. Handlebars, jade, etc.).

If you want to do it with template literals, your only chance is to use `eval`. Please look at this StackOverflow question:
http://stackoverflow.com/questions/29182244/convert-a-string-to-a-template-string

``` js
// home.js
import homeStyl from './home.css';
import homeTpl from './home.html';

document.querySelector('#home').innerHTML = eval('`'+homeTpl.replace(/`/g,'\\`')+'`');
```

Please note that this solution is definitely not optimal, because of at least two reasons:
- it prevents browsers to optimize the script execution because of `eval`
- all the security concerns regarding `eval`

**Comment by Shyam-Chen** [comment]
I solved it with Lodash.

``` js
import template from 'lodash-es/template';

document.querySelector('#home'.innerHTML = template(homeTpl, TplImports)(TplDatas);
```
